### ISSUE TITLE
Error: source sequence is illegal/malformed utf-8

### ISSUE THREAD

**Issue by skull-squadron** [ConradIrwin/jist#38]
Use-case: upload an opaque binary file to a gist. (eg ASCII 8-bit)

String conversion (not) being performed somewhere?

**Comment by ConradIrwin** [comment]
Hey @steakknife. jist is now unmaintained, can you switch to reporting issues on defunkt/gist instead?

That said, in this case, neither gem can help. The gist API is JSON, which means you can only upload files that are valid UTF-8.

**Comment by steakknife** [comment]
Ah-so.  Thanks.

**Comment by steakknife** [comment]
Might want to mark unsupported it at the top of the README.

**Comment by skull-squadron** [comment]
For posterity: https://github.com/defunkt/gist/issues/191

**Comment by ConradIrwin** [comment]
done, thanks.

**Comment by skull-squadron** [comment]
:beer:
